language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "your-git-name"
  - git config user.email "your-email-address"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master